using System;
using System.Collections.Generic;
using System.Linq;
using CUWebinars.Business.Models;
using DateTimeHelper = CUWebinars.Web.Helpers.DateTimeHelper;

namespace CUWebinars.Web.Core.Browsers.Webinars
{
    public class WebinarsSearchDTOAssembler : AbstractDTOAssembler<EntitiesBrowserTableDataDTO, WebinarsBrowserSearchResultDTO>
    {
        private readonly string _echoId;
        private GlobalConfig _globalConfig = GlobalConfig.GlobalConfigSingletonCreator.UniqueInstance;

        public WebinarsSearchDTOAssembler(string echoId)
        {
            _echoId = echoId;
        }

        /// <remarks>
        /// builds the Parent (main) table for Webinars Browser. The Subtable is 
        /// generated by 
        /// </remarks>
        public override EntitiesBrowserTableDataDTO Entity2DTO(WebinarsBrowserSearchResultDTO entity)
        {
            var rowsData = new List<object>();

            foreach (var entry in entity.Entries)
            {
                var numDaysLeft = (entry.Webinar.Date.AddMonths(6) - _globalConfig.UtcNowAsCts).Days;

                var showDateValue = DateTimeHelper.FormatDate(entry.Webinar.Date) + " - " +
                                    DateTimeHelper.FormatTime(entry.Webinar.Date) + " Central Time Zone";

                if (entry.Webinar.Status == WebinarStatus.Recorded)
                {
                    showDateValue = "This OnDemand Webinar has " + numDaysLeft + " days of access remaining.";
                    //if (numDaysLeft > 45)
                    //{
                    //    showDateValue = "About " + Convert.ToInt32(numDaysLeft / (365.25 / 12)) + " months of access remain.";
                    //}
                }

                //var allTopics = entry.Webinar.WebinarTopicXrefs.Contains()
                //.Select(x => x.Description);
                var allTopics = entry.Webinar.WebinarTopicXrefs
                .Select(webinarTopic => webinarTopic.Topic.topicDesc)
                .Aggregate((s1, s2) => s1 + ", " + s2);

                string buildWebinarCol = "<h3><a href='/Webinar/Details/" +
                                        entry.Webinar.idWebinar + "' target='_blank'>" + entry.Webinar.Title + "</a></h3><blockquote><i>";
                buildWebinarCol += showDateValue + "</i><br>";
                buildWebinarCol += entry.Webinar.Description.Length > 200
                                       ? entry.Webinar.Description.Substring(0, 200) + "..."
                                       : entry.Webinar.Description ;

                buildWebinarCol += "<br>";
                buildWebinarCol += "<b>Related Topics: </b>" + string.Join(", ", allTopics)+ "</blockquote>";


                rowsData.Add(new List<object>
                                     {
                                         null,
                                         entry.Webinar.Title,
                                         entry.Webinar.Date.ToShortDateString(),
                                         buildWebinarCol,
                                         "<div class='presenterColumn'>" + entry.Webinar.Presenter.WebUser.FirstName + " " + entry.Webinar.Presenter.WebUser.LastName +
                                         "<br><img src='" + entry.Webinar.Presenter.PhotoThumb +
                                         "' class='presenterImg' /></div>"
                                     });
                //field order of original
                //entry.webinar.idWebinar,
                //buildTitle,
                //entry.Webinar.Date.ToString("MM/dd/yy"),
                //entry.Webinar.Presenter.FullName,
                //entry.RegistrationsCount
            }

            return new EntitiesBrowserTableDataDTO
            {
                iTotalDisplayRecords = entity.FoundCount,
                iTotalRecords = entity.TotalCount,
                aaData = rowsData,
                sEcho = _echoId
            };
        }

        public override WebinarsBrowserSearchResultDTO DTO2Entity(EntitiesBrowserTableDataDTO dto)
        {
            throw new NotImplementedException();
        }
    }

    //public class SearchTableColumns
    //{
    //    public string NotUsed { get; set; }
    //    public string Title { get; set; }
    //    public string Date { get; set; }
    //    public string Description { get; set; }
    //    public string PresenterInfo { get; set; }
    //}
}