using System;
using System.Collections.Generic;
using CUWebinars.Web.Services;
using CUWebinars.Business.Models;

namespace CUWebinars.Web.Core.Browsers.Webinars
{
    public class WebinarsBrowserTableDataDTOAssembler : AbstractDTOAssembler<EntitiesBrowserTableDataDTO, WebinarsBrowserSearchResultDTO>
    {
        private readonly string _echoId;
        IStateService stateService = new StateService();


        public WebinarsBrowserTableDataDTOAssembler(string echoId)
        {
            _echoId = echoId;
        }

        /// <remarks>
        /// builds the Parent (main) table for Webinars Browser. The Subtable is 
        /// generated by 
        ///        public EntitiesBrowserTableDataDTO Entity2DTO(IList<DiscountsBrowserSearchResultDTO> entity)

        /// </remarks>
        public override EntitiesBrowserTableDataDTO Entity2DTO(WebinarsBrowserSearchResultDTO entity)
        {
            var rowsData = new List<object>();
            var user = stateService.GetValue<WebUser>("CurrentUser");
            foreach (var entry in entity.Entries)
            {
                string buildTitle = "";
                buildTitle = entry.Webinar.Title + "<br/>&nbsp;<a href='/Admin/Webinars/ViewFiles/" +
                                        entry.Webinar.idWebinar + "' target='_blank'>[Links]</a>";


                //TODO: Usertype needs to be determined by Claims

                //deprecated method of determining usertype
                //if (CurrentSession.Instance.CurrentWebUser.UserType == UserType.Affiliate)
                //{
                //    buildTitle += "<a href='/Admin/Reports/AffiliateRevenue/" + entry.Webinar.idWebinar +
                //                  "'>[Revenue Report]</a>";
                //}
                //if (CurrentSession.Instance.CurrentWebUser.UserType == UserType.Admin)
                //{
                //    //if (entry.Webinar.HasConnectionInformation && entry.Webinar.Status == WebinarStatus.Scheduled)
                //    //{
                //    //    buildTitle += "&nbsp;<a href='/Admin/Webinars/SendInfo/" + entry.webinar.idWebinar +
                //    //                  "' target='_blank'>[Send Connection Info]</a>";
                //    //}
                //    buildTitle += "&nbsp;<a href='/Admin/Webinars/Edit/" + entry.Webinar.idWebinar + "'>[Edit]</a>";
                //}

                rowsData.Add(new List<object>
                                 {
                                     entry.Webinar.idWebinar,
                                     buildTitle,
                                     entry.Webinar.Date.ToString("MM/dd/yy"),
                                     entry.Webinar.Presenter.WebUser.FullName,
                                     entry.RegistrationsCount
                                 });
            }

            return new EntitiesBrowserTableDataDTO
                       {
                           iTotalDisplayRecords = entity.FoundCount,
                           iTotalRecords = entity.TotalCount,
                           aaData = rowsData,
                           sEcho = _echoId
                       };
        }

        public override WebinarsBrowserSearchResultDTO DTO2Entity(EntitiesBrowserTableDataDTO dto)
        {
            throw new NotImplementedException();
        }
    }
}