namespace CUWebinars.WebUi.Tests.Infrastructure
{
    internal sealed class Constants
    {
        //  Sample Data ("sit" short for system integration test)
        internal const string SitTestAddress = "1 Liberty St";
        internal const string SitTestAltAddress = "220 Wynn Drive";
        internal const string SitTestCity = "Huntsville";
        internal const string SitTestCountry = "USA";
        internal const string SitTestEmailAddress = "Mark_Bennett@ttstrain.com";
        internal const string SitTestEmailAddressDomain = "@ttstrain.com";
        internal const string SitTestFirstName = "John";
        internal const string SitTestInstitutionSuffix = "Bank";
        internal const string SitTestLastName = "Trainer";
        internal const string SitTestPassword = "bennett";
        internal const string SitTestPasswordSameDomainAddress = "f(app5yuK";
        internal const string SitTestPhone = "555-555-555";
        internal const string SitTestState = "AL";
        internal const string SitTestZipCode = "35893";
        internal const string Title = "Mr";

        //  HTML elements
        internal const string EmailInput = "Email";
        //internal const string LoginLinkPath = @"/html/body/section/nav/a";
        internal const string LoginLinkText = "Login";
        //internal const string LogoffLinkPath = "//*[@id=\"logoutForm\"]/a[2]";
        internal const string LogoffLinkText = "[Log Off]";
        internal const string PasswordInput = "Password";
        internal const string SignInButtonInput = "SignInButton";
        

        //
        internal const string FullNameInput = "FullName";
        internal const string GetZipInput = "getZip";
        internal const string RegisterFieldsEmail = "RegisterFields_Email";
        internal const string RegisterFieldsFirstName = "RegisterFields_FirstName";
        internal const string RegisterFieldsLastName = "RegisterFields_LastName";
        internal const string RegisterFieldsConfirmPassword = "RegisterFields.ConfirmPassword";
        internal const string RegisterFieldsInstitution = "RegisterFields_Institution";
        internal const string RegisterFieldsPassword = "RegisterFields_Password";
        internal const string RegisterFieldsPhone = "RegisterFields_BillingAddress_Phone";
        internal const string RegisterFieldsStreetAddress = "RegisterFields_BillingAddress_StreetAddress";
        internal const string RegisterFieldsTitle = "RegisterFields_Title";



        //  Test Query Strings for Import of Orders
        internal const string TestQueryString1 = "idAffiliate=19&BillingAddress.AddressType=Billing&BillingAddress.Name=CDRom Recorded&BillingAddress.Phone=(256) 837-6110&BillingAddress.StreetAddress=220 Wynn Drive&BillingAddress.StreetAddress2= &BillingAddress.City=Huntsville&BillingAddress.Zip=35893&BillingAddress.State=AL&BillingAddress.Country=USA&ShippingAddress.AddressType=Shipping&ShippingAddress.Name=CDRom Recorded&ShippingAddress.Phone=(256) 837-6110&ShippingAddress.StreetAddress=220 Wynn Drive&ShippingAddress.StreetAddress2= &ShippingAddress.City=Huntsville&ShippingAddress.Zip=35893&ShippingAddress.State=AL&ShippingAddress.Country=USA&Email=CDRom@Recorded1.com&Title=VP/Chief Compliance Officer&Institution=Redstone Federal Credit Union&FirstName=CDRom&LastName=Recorded&idRegType=99&idWebinar=401";
        internal const string TestQueryString2 = "idAffiliate=19&BillingAddress.AddressType=Billing&BillingAddress.Name=OnDemandOnly Recorded&BillingAddress.Phone=(256) 837-6110&BillingAddress.StreetAddress=220 Wynn Drive&BillingAddress.StreetAddress2= &BillingAddress.City=Huntsville&BillingAddress.Zip=35893&BillingAddress.State=AL&BillingAddress.Country=USA&ShippingAddress.AddressType=Shipping&ShippingAddress.Name=OnDemandOnly Recorded&ShippingAddress.Phone=(256) 837-6110&ShippingAddress.StreetAddress=220 Wynn Drive&ShippingAddress.StreetAddress2= &ShippingAddress.City=Huntsville&ShippingAddress.Zip=35893&ShippingAddress.State=AL&ShippingAddress.Country=USA&Email=OnDemandOnly@Recorded1.com&Title=VP/Chief Compliance Officer&Institution=Redstone Federal Credit Union&FirstName=OnDemandOnly&LastName=Recorded&idRegType=98&idWebinar=401";
        internal const string TestQueryString3 = "idAffiliate=19&BillingAddress.AddressType=Billing&BillingAddress.Name=Premier UpcomingHasConnInfo&BillingAddress.Phone=(256) 837-6110&BillingAddress.StreetAddress=220 Wynn Drive&BillingAddress.StreetAddress2= &BillingAddress.City=Huntsville&BillingAddress.Zip=35893&BillingAddress.State=AL&BillingAddress.Country=USA&ShippingAddress.AddressType=Shipping&ShippingAddress.Name=Premier UpcomingHasConnInfo&ShippingAddress.Phone=(256) 837-6110&ShippingAddress.StreetAddress=220 Wynn Drive&ShippingAddress.StreetAddress2= &ShippingAddress.City=Huntsville&ShippingAddress.Zip=35893&ShippingAddress.State=AL&ShippingAddress.Country=USA&Email=PremierHasConnectionInfo@ttstrain1.com&Title=VP/Chief Compliance Officer&Institution=Redstone Federal Credit Union&FirstName=Premier&LastName=UpcomingHasConnInfo&idRegType=101&idWebinar=701";
        internal const string TestQueryString4 = "idAffiliate=19&BillingAddress.AddressType=Billing&BillingAddress.Name=LivePlus UpcomingHasConnInfo&BillingAddress.Phone=(256) 837-6110&BillingAddress.StreetAddress=220 Wynn Drive&BillingAddress.StreetAddress2= &BillingAddress.City=Huntsville&BillingAddress.Zip=35893&BillingAddress.State=AL&BillingAddress.Country=USA&ShippingAddress.AddressType=Shipping&ShippingAddress.Name=LivePlus UpcomingHasConnInfo&ShippingAddress.Phone=(256) 837-6110&ShippingAddress.StreetAddress=220 Wynn Drive&ShippingAddress.StreetAddress2= &ShippingAddress.City=Huntsville&ShippingAddress.Zip=35893&ShippingAddress.State=AL&ShippingAddress.Country=USA&Email=LivePlusOnDemandHasConnectionInfo@ttstrain1.com&Title=VP/Chief Compliance Officer&Institution=Redstone Federal Credit Union&FirstName=LivePlus&LastName=UpcomingHasConnInfo&idRegType=100&idWebinar=701";
        internal const string TestQueryString5 = "idAffiliate=19&BillingAddress.AddressType=Billing&BillingAddress.Name=CDRom UpcomingHasConnInfo&BillingAddress.Phone=(256) 837-6110&BillingAddress.StreetAddress=220 Wynn Drive&BillingAddress.StreetAddress2= &BillingAddress.City=Huntsville&BillingAddress.Zip=35893&BillingAddress.State=AL&BillingAddress.Country=USA&ShippingAddress.AddressType=Shipping&ShippingAddress.Name=CDRom UpcomingHasConnInfo&ShippingAddress.Phone=(256) 837-6110&ShippingAddress.StreetAddress=220 Wynn Drive&ShippingAddress.StreetAddress2= &ShippingAddress.City=Huntsville&ShippingAddress.Zip=35893&ShippingAddress.State=AL&ShippingAddress.Country=USA&Email=CDRomHasConnectionInfo@ttstrain1.com&Title=VP/Chief Compliance Officer&Institution=Redstone Federal Credit Union&FirstName=CDRom&LastName=UpcomingHasConnInfo&idRegType=99&idWebinar=701";
        internal const string TestQueryString6 = "idAffiliate=19&BillingAddress.AddressType=Billing&BillingAddress.Name=RecordedOnly UpcomingHasConnInfo&BillingAddress.Phone=(256) 837-6110&BillingAddress.StreetAddress=220 Wynn Drive&BillingAddress.StreetAddress2= &BillingAddress.City=Huntsville&BillingAddress.Zip=35893&BillingAddress.State=AL&BillingAddress.Country=USA&ShippingAddress.AddressType=Shipping&ShippingAddress.Name=RecordedOnly UpcomingHasConnInfo&ShippingAddress.Phone=(256) 837-6110&ShippingAddress.StreetAddress=220 Wynn Drive&ShippingAddress.StreetAddress2= &ShippingAddress.City=Huntsville&ShippingAddress.Zip=35893&ShippingAddress.State=AL&ShippingAddress.Country=USA&Email=RecordedOnlyHasConnectionInfo@ttstrain1.com&Title=VP/Chief Compliance Officer&Institution=Redstone Federal Credit Union&FirstName=RecordedOnly&LastName=UpcomingHasConnInfo&idRegType=98&idWebinar=701";
        internal const string TestQueryString7 = "idAffiliate=19&BillingAddress.AddressType=Billing&BillingAddress.Name=LiveOnly UpcomingHasConnInfo&BillingAddress.Phone=(256) 837-6110&BillingAddress.StreetAddress=220 Wynn Drive&BillingAddress.StreetAddress2= &BillingAddress.City=Huntsville&BillingAddress.Zip=35893&BillingAddress.State=AL&BillingAddress.Country=USA&ShippingAddress.AddressType=Shipping&ShippingAddress.Name=LiveOnly UpcomingHasConnInfo&ShippingAddress.Phone=(256) 837-6110&ShippingAddress.StreetAddress=220 Wynn Drive&ShippingAddress.StreetAddress2= &ShippingAddress.City=Huntsville&ShippingAddress.Zip=35893&ShippingAddress.State=AL&ShippingAddress.Country=USA&Email=LiveOnlyHasConnectionInfo@ttstrain1.com&Title=VP/Chief Compliance Officer&Institution=Redstone Federal Credit Union&FirstName=LiveOnly&LastName=UpcomingHasConnInfo&idRegType=97&idWebinar=701";
        internal const string TestQueryString8 = "idAffiliate=19&BillingAddress.AddressType=Billing&BillingAddress.Name=Premier UpcomingNoConnInfo&BillingAddress.Phone=(256) 837-6110&BillingAddress.StreetAddress=220 Wynn Drive&BillingAddress.StreetAddress2= &BillingAddress.City=Huntsville&BillingAddress.Zip=35893&BillingAddress.State=AL&BillingAddress.Country=USA&ShippingAddress.AddressType=Shipping&ShippingAddress.Name=Premier UpcomingNoConnInfo&ShippingAddress.Phone=(256) 837-6110&ShippingAddress.StreetAddress=220 Wynn Drive&ShippingAddress.StreetAddress2= &ShippingAddress.City=Huntsville&ShippingAddress.Zip=35893&ShippingAddress.State=AL&ShippingAddress.Country=USA&Email=Premier@UpcomingNoConnInfo1.com&Title=VP/Chief Compliance Officer&Institution=Redstone Federal Credit Union&FirstName=Premier&LastName=UpcomingNoConnInfo&idRegType=101&idWebinar=404";
        internal const string TestQueryString9 = "idAffiliate=19&BillingAddress.AddressType=Billing&BillingAddress.Name=LivePlusOnDemand UpcomingNoConnInfo&BillingAddress.Phone=(256) 837-6110&BillingAddress.StreetAddress=220 Wynn Drive&BillingAddress.StreetAddress2= &BillingAddress.City=Huntsville&BillingAddress.Zip=35893&BillingAddress.State=AL&BillingAddress.Country=USA&ShippingAddress.AddressType=Shipping&ShippingAddress.Name=LivePlusOnDemand UpcomingNoConnInfo&ShippingAddress.Phone=(256) 837-6110&ShippingAddress.StreetAddress=220 Wynn Drive&ShippingAddress.StreetAddress2= &ShippingAddress.City=Huntsville&ShippingAddress.Zip=35893&ShippingAddress.State=AL&ShippingAddress.Country=USA&Email=LivePlusOnDemand@UpcomingNoConnInfo1.com&Title=VP/Chief Compliance Officer&Institution=Redstone Federal Credit Union&FirstName=LivePlusOnDemand&LastName=UpcomingNoConnInfo&idRegType=100&idWebinar=404";
        internal const string TestQueryString10 = "idAffiliate=19&BillingAddress.AddressType=Billing&BillingAddress.Name=CDRom UpcomingNoConnInfo&BillingAddress.Phone=(256) 837-6110&BillingAddress.StreetAddress=220 Wynn Drive&BillingAddress.StreetAddress2= &BillingAddress.City=Huntsville&BillingAddress.Zip=35893&BillingAddress.State=AL&BillingAddress.Country=USA&ShippingAddress.AddressType=Shipping&ShippingAddress.Name=CDRom UpcomingNoConnInfo&ShippingAddress.Phone=(256) 837-6110&ShippingAddress.StreetAddress=220 Wynn Drive&ShippingAddress.StreetAddress2= &ShippingAddress.City=Huntsville&ShippingAddress.Zip=35893&ShippingAddress.State=AL&ShippingAddress.Country=USA&Email=CDRom@UpcomingNoConnInfo1.com&Title=VP/Chief Compliance Officer&Institution=Redstone Federal Credit Union&FirstName=CDRom&LastName=UpcomingNoConnInfo&idRegType=99&idWebinar=404";
        internal const string TestQueryString11 = "idAffiliate=19&BillingAddress.AddressType=Billing&BillingAddress.Name=RecordedOnly UpcomingNoConnInfo&BillingAddress.Phone=(256) 837-6110&BillingAddress.StreetAddress=220 Wynn Drive&BillingAddress.StreetAddress2= &BillingAddress.City=Huntsville&BillingAddress.Zip=35893&BillingAddress.State=AL&BillingAddress.Country=USA&ShippingAddress.AddressType=Shipping&ShippingAddress.Name=RecordedOnly UpcomingNoConnInfo&ShippingAddress.Phone=(256) 837-6110&ShippingAddress.StreetAddress=220 Wynn Drive&ShippingAddress.StreetAddress2= &ShippingAddress.City=Huntsville&ShippingAddress.Zip=35893&ShippingAddress.State=AL&ShippingAddress.Country=USA&Email=RecordedOnly@ttstrain1.com&Title=VP/Chief Compliance Officer&Institution=Redstone Federal Credit Union&FirstName=RecordedOnly&LastName=UpcomingNoConnInfo&idRegType=98&idWebinar=404";
        internal const string TestQueryString12 = "idAffiliate=19&BillingAddress.AddressType=Billing&BillingAddress.Name=LiveOnly UpcomingNoConnInfo&BillingAddress.Phone=(256) 837-6110&BillingAddress.StreetAddress=220 Wynn Drive&BillingAddress.StreetAddress2= &BillingAddress.City=Huntsville&BillingAddress.Zip=35893&BillingAddress.State=AL&BillingAddress.Country=USA&ShippingAddress.AddressType=Shipping&ShippingAddress.Name=LiveOnly UpcomingNoConnInfo&ShippingAddress.Phone=(256) 837-6110&ShippingAddress.StreetAddress=220 Wynn Drive&ShippingAddress.StreetAddress2= &ShippingAddress.City=Huntsville&ShippingAddress.Zip=35893&ShippingAddress.State=AL&ShippingAddress.Country=USA&Email=LiveOnly@ttstrain1.com&Title=VP/Chief Compliance Officer&Institution=Redstone Federal Credit Union&FirstName=LiveOnly&LastName=UpcomingNoConnInfo&idRegType=97&idWebinar=404";
    }
}
