--DELETE BankWebinars.dbo.Affiliate WHERE idUserAff > 19
--DELETE BankWebinars.dbo.[Order] WHERE idUser > 19
--DELETE BankWebinars.dbo.WebUser WHERE email NOT IN ('affiliate@ttstrain.com') AND UserType <> 3
UPDATE  dbo.Affiliate
SET     ttsDomain = LOWER(ttsDomain) ,
        WebBanner = '' ,
        Logo = 'http://ttsmedia.ttstrain.com/images/logo_' + LOWER(ttsDomain) + '.png' 
        
WHERE   idUserAff > 0

USE [BankWebinars]
GO
SELECT * FROM dbo.Affiliate WHERE idUserAff = 62
DELETE FROM dbo.[Order] WHERE BillingEmail ='affiliate@ttstrain.com'
DELETE FROM dbo.[Order] WHERE BillingEmail ='sfisher@mibankers.com'
DELETE FROM dbo.[Order] WHERE BillingEmail ='deb@cftnow.org'
DELETE FROM dbo.[Order] WHERE BillingEmail ='mataylor@cbao.com'
DELETE FROM dbo.[Order] WHERE BillingEmail ='Sandy@cftncs.org'
DELETE FROM dbo.[Order] WHERE BillingEmail ='shannon@cftum.org'
DELETE FROM dbo.[Order] WHERE BillingEmail ='rhondap@cftws.org'
DELETE FROM dbo.[Order] WHERE BillingEmail ='claguna@mdc.edu'
DELETE FROM dbo.[Order] WHERE BillingEmail ='info@cftva.org'
DELETE FROM dbo.[Order] WHERE BillingEmail ='dbaker@cftgpr.org'
DELETE FROM dbo.[Order] WHERE BillingEmail ='cftrny@aol.com'
DELETE FROM dbo.[Order] WHERE BillingEmail ='dphelps@cftuny.com'
DELETE FROM dbo.[Order] WHERE BillingEmail ='holder@ttstrain.com'
DELETE FROM dbo.[Order] WHERE BillingEmail ='claguna@mdc.edu'
DELETE FROM dbo.[Order] WHERE BillingEmail ='cathy@tristatecft.org'
DELETE FROM dbo.[Order] WHERE BillingEmail ='help@ozarkempirecft.org'
DELETE FROM dbo.[Order] WHERE BillingEmail ='ddriggers@gabankers.com'
DELETE FROM dbo.[Order] WHERE BillingEmail ='liz@ncbankers.org'
DELETE FROM dbo.[Order] WHERE BillingEmail ='jk.hopkins@verizon.net'
DELETE FROM dbo.[Order] WHERE BillingEmail ='ekilty@indianabankers.org'
DELETE FROM dbo.[Order] WHERE BillingEmail ='anewsom@oregonbankers.com'
DELETE FROM dbo.[Order] WHERE BillingEmail ='nvbankers@att.net'
DELETE FROM dbo.[Order] WHERE BillingEmail ='cbross@retrainingcenter.com'
DELETE FROM dbo.[Order] WHERE BillingEmail ='kbennett@ttstrain.com'
DELETE FROM dbo.[Order] WHERE BillingEmail ='wrosenthal@idahobankers.org'
DELETE FROM dbo.[Order] WHERE BillingEmail ='dpharr@mycbaa.com'
DELETE FROM dbo.[Order] WHERE BillingEmail ='bourgeois@lba.org'
DELETE FROM dbo.[Order] WHERE BillingEmail ='jdeal@sdba.com'
DELETE FROM dbo.[Order] WHERE BillingEmail ='datkinson@wvbankers.org'
DELETE FROM dbo.[Order] WHERE BillingEmail ='bwilkes@uba.org'
DELETE FROM dbo.[Order] WHERE BillingEmail ='cheryl@wyomingbankers.com'
DELETE FROM dbo.[Order] WHERE BillingEmail ='dorothy@ndba.com'
DELETE FROM dbo.[Order] WHERE BillingEmail ='tanya@cftea.org'
DELETE FROM dbo.[Order] WHERE BillingEmail ='greg@gregsouther.com'
DELETE FROM dbo.[Order] WHERE BillingEmail ='cfleming@vabankers.org'
DELETE FROM dbo.[Order] WHERE BillingEmail ='jamie.zussman@rate-watch.com'
DELETE FROM dbo.[Order] WHERE BillingEmail ='honey@interaction-training.com'
DELETE FROM dbo.[Order] WHERE BillingEmail ='bhoffman@ilbanker.com'
DELETE FROM dbo.[Order] WHERE BillingEmail ='kimp@minnbankers.com'
DELETE FROM dbo.[Order] WHERE BillingEmail ='jstone@ilfi.org'
DELETE FROM dbo.[Order] WHERE BillingEmail ='elegg@nyba.com'
DELETE FROM dbo.[Order] WHERE BillingEmail ='nelsenm@ctbank.com'
DELETE FROM dbo.[Order] WHERE BillingEmail ='tduncan@massbankers.org'
DELETE FROM dbo.[Order] WHERE BillingEmail ='stracy@nhbankers.com'
DELETE FROM dbo.[Order] WHERE BillingEmail ='nloppnow@wisbank.com'
DELETE FROM dbo.[Order] WHERE BillingEmail ='cgoncalves@njbankers.com'
DELETE FROM dbo.[Order] WHERE BillingEmail ='kami.taylor@arkbankers.org'
DELETE FROM dbo.[Order] WHERE BillingEmail ='pam@montanabankers.com'
DELETE FROM dbo.[Order] WHERE BillingEmail ='Liz@wabankers.com'
DELETE FROM dbo.[Order] WHERE BillingEmail ='scottspiewak@newswatchmedia.com'
DELETE FROM dbo.[Order] WHERE BillingEmail ='dschaefer@nmbankers.com'
DELETE FROM dbo.[Order] WHERE BillingEmail ='leaton@calbankers.com'
DELETE FROM dbo.[Order] WHERE BillingEmail ='auroratrainingadvantage@gmail.com'
DELETE FROM dbo.[Order] WHERE BillingEmail ='sanal@trainingpitstop.com'
DELETE FROM dbo.[Order] WHERE BillingEmail ='dburnett@iowabankers.com'
DELETE FROM dbo.[Order] WHERE BillingEmail ='sdspec@aol.com'
DELETE FROM dbo.[Order] WHERE BillingEmail ='pcross@kybanks.com'
DELETE FROM dbo.[Order] WHERE BillingEmail ='mtaylor@ksbankers.com'
DELETE FROM dbo.[Order] WHERE BillingEmail ='cunews@cunews.com'

ALTER TABLE [dbo].[Address] DROP CONSTRAINT [FK_dbo.Address_dbo.WebUser_idUser]
GO

alter table dbo.Address 
  add constraint [FK_dbo.Address_dbo.WebUser_idUser]
      foreign key (idUser) 
      references dbo.WebUser(idUser)
      on delete cascade 
      on update cascade



update WebUser set idUser = 19 where email = 'affiliate@ttstrain.com'
update WebUser set idUser = 29 where email = 'sfisher@mibankers.com'
update WebUser set idUser = 62 where email = 'deb@cftnow.org'
update WebUser set idUser = 375 where email = 'mataylor@cbao.com'
update WebUser set idUser = 376 where email = 'Sandy@cftncs.org'
update WebUser set idUser = 379 where email = 'shannon@cftum.org'
update WebUser set idUser = 380 where email = 'rhondap@cftws.org'
update WebUser set idUser = 383 where email = 'claguna@mdc.edu'
update WebUser set idUser = 384 where email = 'info@cftva.org'
update WebUser set idUser = 385 where email = 'dbaker@cftgpr.org'
update WebUser set idUser = 386 where email = 'cftrny@aol.com'
update WebUser set idUser = 387 where email = 'dphelps@cftuny.com'
update WebUser set idUser = 394 where email = 'holder@ttstrain.com'
update WebUser set idUser = 395 where email = 'claguna@mdc.edu'
update WebUser set idUser = 396 where email = 'cathy@tristatecft.org'
update WebUser set idUser = 963 where email = 'help@ozarkempirecft.org'
update WebUser set idUser = 1775 where email = 'ddriggers@gabankers.com'
update WebUser set idUser = 1827 where email = 'liz@ncbankers.org'
update WebUser set idUser = 2550 where email = 'jk.hopkins@verizon.net'
update WebUser set idUser = 2610 where email = 'ekilty@indianabankers.org'
update WebUser set idUser = 2636 where email = 'anewsom@oregonbankers.com'
update WebUser set idUser = 2984 where email = 'nvbankers@att.net'
update WebUser set idUser = 2986 where email = 'cbross@retrainingcenter.com'
update WebUser set idUser = 2988 where email = 'kbennett@ttstrain.com'
update WebUser set idUser = 2989 where email = 'wrosenthal@idahobankers.org'
update WebUser set idUser = 2990 where email = 'dpharr@mycbaa.com'
update WebUser set idUser = 2992 where email = 'bourgeois@lba.org'
update WebUser set idUser = 2993 where email = 'jdeal@sdba.com'
update WebUser set idUser = 2994 where email = 'datkinson@wvbankers.org'
update WebUser set idUser = 2997 where email = 'bwilkes@uba.org'
update WebUser set idUser = 10749 where email = 'cheryl@wyomingbankers.com'
update WebUser set idUser = 11240 where email = 'dorothy@ndba.com'
update WebUser set idUser = 11464 where email = 'tanya@cftea.org'
update WebUser set idUser = 12014 where email = 'greg@gregsouther.com'
update WebUser set idUser = 14577 where email = 'cfleming@vabankers.org'
update WebUser set idUser = 16132 where email = 'jamie.zussman@rate-watch.com'
update WebUser set idUser = 16392 where email = 'honey@interaction-training.com'
update WebUser set idUser = 17146 where email = 'bhoffman@ilbanker.com'
update WebUser set idUser = 17147 where email = 'kimp@minnbankers.com'
update WebUser set idUser = 17148 where email = 'jstone@ilfi.org'
update WebUser set idUser = 17149 where email = 'elegg@nyba.com'
update WebUser set idUser = 17150 where email = 'nelsenm@ctbank.com'
update WebUser set idUser = 17151 where email = 'tduncan@massbankers.org'
update WebUser set idUser = 17152 where email = 'stracy@nhbankers.com'
update WebUser set idUser = 17430 where email = 'nloppnow@wisbank.com'
update WebUser set idUser = 17431 where email = 'cgoncalves@njbankers.com'
update WebUser set idUser = 19741 where email = 'kami.taylor@arkbankers.org'
update WebUser set idUser = 20385 where email = 'pam@montanabankers.com'
update WebUser set idUser = 21066 where email = 'Liz@wabankers.com'
update WebUser set idUser = 22805 where email = 'scottspiewak@newswatchmedia.com'
update WebUser set idUser = 23801 where email = 'dschaefer@nmbankers.com'
update WebUser set idUser = 24033 where email = 'leaton@calbankers.com'
update WebUser set idUser = 24870 where email = 'auroratrainingadvantage@gmail.com'
update WebUser set idUser = 25993 where email = 'sanal@trainingpitstop.com'
update WebUser set idUser = 26276 where email = 'dburnett@iowabankers.com'
update WebUser set idUser = 26966 where email = 'sdspec@aol.com'
update WebUser set idUser = 27391 where email = 'pcross@kybanks.com'
update WebUser set idUser = 27842 where email = 'mtaylor@ksbankers.com'
update WebUser set idUser = 31267 where email = 'cunews@cunews.com'


INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (19, 1, N'http://www.ttstrain.com/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N'', N'', N'bankwebinars', NULL, NULL, N'Total Training Solutions', N'billed', N'http://ttsmedia.ttstrain.com/images/logo_bankwebinars', N'Mark', N'608-849-5563', N'affiliate@ttstrain.com', N'', N'PO Box 310', N'affiliate@ttstrain.com', N'608-849-5563', N'Mark', N'None')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (29, 4, N'http://www.mibankers.com/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N'', N'', N'mibankers', NULL, NULL, N'Michigan Bankers Association', N'Aff       ', N'http://ttsmedia.ttstrain.com/images/logo_mibankers', N'Stephanie Fisher', N'517-342-9057', N'sfisher@mibankers.com', N'517-342-9057', N'507 S Grand Ave', N'sfisher@mibankers.com', N'517-342-9074', N'Stephanie Fisher', N'Weekly')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (62, 1, N'http://www.cftacs.org/', N'', N'<p><strong>HEADQUARTERS:</strong> 33 Broadway P.O. Box 969 Norwich, CT 06360<br><strong>TOLL FREE PHONE:</strong> 800-795-5242<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N'', N'', N'cftnow', NULL, NULL, N'CFT - Atlantic & Central States', N'billed', N'http://ttsmedia.ttstrain.com/images/logo_cftnow', N'Deb Rondeau', N'860-383-1176', N'deb@cftnow.org', N'860-823-1410', N'PO Box 969', N'deb@cftnow.org', N'860-383-1176', N'Deb Rondeau', N'None')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (375, 4, N'http://www.cbao.com/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N'', N'', N'cbao', NULL, NULL, N'Community Bankers Association of Ohio', N'billed', N'http://ttsmedia.ttstrain.com/images/logo_cbao', N'Dawn Hoover', N'614-846-8124', N'dmhoover@cbao.com', N'', N'1060 Kingsmill Pkwy', N'dmhoover@cbao.com', N'614-846-8124', N'Dawn Hoover', N'None')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (376, 1, N'http://www.cftncs.org/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N'', N'', N'cftncs', NULL, NULL, N'CFT - North Central States', N'billed', N'http://ttsmedia.ttstrain.com/images/logo_cftncs', N'Sandy Kuehn', N'414-332-6468', N'Sandy@cftncs.org', N'', N'177 E Silver Spring Drive, Suite 400', N'Sandy@cftncs.org', N'414-332-6468', N'Sandy Kuehn', N'Weekly')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (379, 1, N'http://www.cftum.org/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N'', N'', N'cftum', NULL, NULL, N'CFT - Upper Midwest', N'billed', N'http://ttsmedia.ttstrain.com/images/logo_cftum', N'Shannon Duffy', N'507-249-2045', N'shannon@cftum.org', N'', N'PO Box 524', N'shannon@cftum.org', N'507-249-2045', N'Shannon Duffy', N'Daily')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (380, 1, N'http://www.cftws.org/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N'', N'', N'cftws', NULL, NULL, N'CFT - Western States', N'billed', N'http://ttsmedia.ttstrain.com/images/logo_cftws', N'Rhonda Potter', N'303-825-1590', N'rhondap@cftws.org', N'303-629-1591', N'5310 Ward Road, Suite 211', N'retas@cftws.org', N'303-825-1590', N'Reta Selanders', N'Weekly')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (383, 1, N'http://www.sfcft.org/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N'', N'', N'sfcft', NULL, NULL, N'CFT Southeastern', N'billed', N'http://ttsmedia.ttstrain.com/images/logo_sfcft', N'Connie Laguna', N'305-237-3051', N'claguna@mdc.edu', N'', N'245 NE 4th St, Room 3704', N'claguna@mdc.edu', N'305-237-3051', N'Connie Laguna', N'Weekly')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (384, 1, N'http://www.cftva.org/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N'', N'', N'cftva', NULL, NULL, N'CFT - Virginia', N'billed', N'http://ttsmedia.ttstrain.com/images/logo_cftva', N'Pam Owens', N'757-466-1830', N'pam@cftea.org', N'', N'P. O. Box 14399', N'info@cftva.org', N'757-466-1830', N'Pam Owens', N'None')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (385, 1, N'http://www.cftgpr.org/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N'', N'', N'cftgpr', NULL, NULL, N'CFT - Great Plains Region', N'billed', N'http://ttsmedia.ttstrain.com/images/logo_cftgpr', N'Debbie Baker', N'316-269-2980', N'dbaker@cftgpr.org', N'', N'Address', N'dbaker@cftgpr.org', N'316-269-2980', N'Debbie Baker', N'Weekly')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (386, 1, N' ', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N' ', N' ', N'ttsholder', N' ', N' ', N' ', N' ', N'http://ttsmedia.ttstrain.com/images/logo_ttsholder', N'CFT-RNY Admin', N'716-847-6430', N'cftrny@aol.com', N'', N'237 Main St., Suite 300', N'cftrny@aol.com', N'716-847-6430', N'CFT-RNY Admin', N'None')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (387, 1, N'http://www.cftuny.com/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N'', N'', N'cftuny', NULL, NULL, N'CFT - Upstate New York', N'billed', N'http://ttsmedia.ttstrain.com/images/logo_cftuny', N'CFT -Upstate NY', N'315-233-7242', N'dphelps@cftuny.com', N'315-233-7244', N'1201 E. Fayette St.', N'dphelps@cftuny.com', N'315-233-7242', N'CFT -Upstate NY', N'None')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (394, 1, N' ', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N' ', N' ', N'ttsholder', NULL, NULL, N'nj', N'nj', N'http://ttsmedia.ttstrain.com/images/logo_ttsholder', N'CFT-NJ Admin', N'Phone', N'holder@ttstrain.com', N'', N'Address', N'holder@ttstrain.com', N'Phone', N'CFT-NJ Admin', N'None')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (395, 1, N'http://www.cft-flsc.org/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N'', N'', N'cft-flsc', NULL, NULL, N'CFT Southeastern', N'billed', N'http://ttsmedia.ttstrain.com/images/logo_cft-flsc', N'Connie Laguna', N'305-237-3051', N'claguna@mdc.edu', N'', N'245 NE 4th St, Room 3704', N'claguna@mdc.edu', N'305-237-3051', N'Connie Laguna', N'Daily')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (396, 1, N'http://www.tristatecft.org/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N'', N'', N'cftts', NULL, NULL, N'Tristate CFT', N'billed', N'http://ttsmedia.ttstrain.com/images/logo_cftts', N'Cathy Richardson', N'513-621-8408', N'cathy@tristatecft.org', N'', N'602 Main St, Suite 711', N'chris@tristatecft.org', N'513-621-8408', N'Chris Kelso', N'Daily')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (963, 1, N'http://www.ozarkempirecft.org/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N'', N'', N'cftoz', NULL, NULL, N'Ozark Empire CFT', N'billed', N'http://ttsmedia.ttstrain.com/images/logo_cftoz', N'Steve Sanpaolo', N'417-818-7933', N'help@ozarkempirecft.org', N'', N'3826 W Kingsley', N'help@ozarkempirecft.org', N'417-818-7933', N'Steve Sanpaolo', N'Daily')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (1775, 1, N'http://www.gabankers.com/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N'', N'', N'gabankers', NULL, NULL, N'Georgia Bankers Association', N'Aff       ', N'http://ttsmedia.ttstrain.com/images/logo_gabankers', N'Danielle Driggers', N'404.420.2002', N'ddriggers@gabankers.com', N'', N'50 Hurt Plaza, Suite 1050', N'ddriggers@gabankers.com', N'404.420.2002', N'Danielle Driggers', N'None')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (1827, 1, N'http://www.ncbankers.org/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N'', N'', N'ncbankers', NULL, NULL, N'North Carolina Bankers Association', N'Aff       ', N'http://ttsmedia.ttstrain.com/images/logo_ncbankers', N'Elizabeth C. Dobbins-Smith', N'800-662-7044', N'liz@ncbankers.org', N'919-881-9909', N'3601 Haworth Drive', N'liz@ncbankers.org', N'800-662-7044', N'Elizabeth C. Dobbins-Smith', N'Daily')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (2550, 1, N'http://www.califprofdevel.com/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N'', N'', N'cpd', NULL, NULL, N'California Professional Development', N'Aff       ', N'http://ttsmedia.ttstrain.com/images/logo_cpd', N'Jim Hopkins', N'562-943-5776', N'jk.hopkins@verizon.net', N'', N'15425 Wilmaglen Drive', N'jk.hopkins@verizon.net', N'562-943-5776', N'Jim Hopkins', N'None')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (2610, 3, N'http://www.IndianaBankers.org/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N'', N'', N'indianabankers', NULL, NULL, N'Indiana Bankers Association', N'billed', N'http://ttsmedia.ttstrain.com/images/logo_indianabankers', N'Mitzi Christian', N'317-387-9380', N'mchristian@IndianaBankers.org', N'317-387-9374', N'6925 Parkdale Place', N'mchristian@IndianaBankers.org', N'317-387-9380', N'Mitzi Christian', N'None')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (2636, 1, N'http://www.oregonbankers.com/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N'', N'', N'oregonbankers', NULL, NULL, N'Oregon Bankers Association', N'Aff       ', N'http://ttsmedia.ttstrain.com/images/logo_oregonbankers', N'Jo Ann Wright', N'503-581-3522', N'jwright@oregonbankers.com', N'', N'PO Box 13429', N'jwright@oregonbankers.com', N'503-581-3522', N'Jo Ann Wright', N'None')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (2984, 1, N'http://www.nvbankers.org/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N'', N'', N'nvbankers', NULL, NULL, N'Nevada Bankers Association', N'Aff       ', N'http://ttsmedia.ttstrain.com/images/logo_nvbankers', N'Bill Uffelman', N'702-233-8607', N'nvbankers@att.net', N'', N'PO 27588', N'nvbankers@att.net', N'702-233-8607', N'Bill Uffelman', N'None')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (2986, 1, N'http://www.retrainingcenter.com/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N'', N'', N'abtc', NULL, NULL, N'American Bank Training Center', N'billed', N'http://ttsmedia.ttstrain.com/images/logo_abtc', N'Charlie Bross', N'770-410-1219', N'cbross@retrainingcenter.com', N'', N'', N'cbross@retrainingcenter.com', N'770-410-1219', N'Charlie Bross', N'None')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (2988, 1, N'http://www.ttstrain.com/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N'', N'', N'ttskb', NULL, NULL, N'BankWebinars', N'Aff       ', N'http://ttsmedia.ttstrain.com/images/logo_ttskb', N'Kyle Bennett', N'800-831-0678', N'kbennett@ttstrain.com', N'800-831-3776', N'PO Box 310', N'kbennett@ttstrain.com', N'800-831-0678', N'Kyle Bennett', N'Daily')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (2989, 1, N'http://www.idahobankers.org/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N'', N'', N'idahobankers', NULL, NULL, N'Idaho Bankers Association', N'Aff       ', N'http://ttsmedia.ttstrain.com/images/logo_idahobankers', N'Wisti Rosenthal', N'208-342-8282', N'wrosenthal@idahobankers.org', N'	208-342-8044', N'PO Box 638', N'wrosenthal@idahobankers.org', N'208-342-8282', N'Wisti Rosenthal', N'Daily')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (2990, 1, N'http://www.alabamabankers.org/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N'', N'', N'alabamabankers', NULL, NULL, N'Alabama Bankers Association', N'Aff       ', N'http://ttsmedia.ttstrain.com/images/logo_alabamabankers', N'Melissa Martin', N'334-834-1890', N'mmartin@alabamabankers.org', N'334-834-4443', N'534 Adams Avenue', N'mmartin@alabamabankers.org', N'334-834-1890', N'Melissa Martin', N'None')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (2992, 1, N'http://www.lba.org/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N'', N'', N'lba', NULL, NULL, N'Louisiana Bankers Association', N'Aff       ', N'http://ttsmedia.ttstrain.com/images/logo_lba', N'Marcy Bourgeois', N'225-214-4831', N'bourgeois@lba.org', N'225-343-3159', N'PO Box 2871', N'bourgeois@lba.org', N'225-214-4831', N'Marcy Bourgeois', N'None')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (2993, 1, N'http://www.sdba.com/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N'', N'', N'sdba', NULL, NULL, N'South Dakota Bankers Association', N'Aff       ', N'http://ttsmedia.ttstrain.com/images/logo_sdba', N'Joan Deal', N'605-224-1653', N'jdeal@sdba.com', N'605-224-7835', N'PO Box 1081', N'nkepford@sdba.com', N'605-224-1653', N'Nadine Kepford', N'Daily')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (2994, 1, N'http://www.wvbankers.org/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N'', N'', N'wvbankers', NULL, NULL, N'West Virginia Bankers Association', N'Aff       ', N'http://ttsmedia.ttstrain.com/images/logo_wvbankers', N'Donna Atkinson', N'304-343-8838', N'datkinson@wvbankers.org', N'304-343-9749', N'120 Washington St E', N'datkinson@wvbankers.org', N'304-343-8838', N'Donna Atkinson', N'Daily')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (2997, 1, N'http://www.uba.org/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N'', N'', N'uba', NULL, NULL, N'Utah Bankers Association', N'billed', N'http://ttsmedia.ttstrain.com/images/logo_uba', N'Becky Wilkes', N'801-214-7724', N'bwilkes@uba.org', N'801-364-4495', N'185 S State St', N'bwilkes@uba.org', N'801-214-7724', N'Becky Wilkes', N'None')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (10749, 1, N'http://www.wyomingbankers.com/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N'', N'', N'wyomingbankers', NULL, NULL, N'Wyoming Bankers Association', N'Aff       ', N'http://ttsmedia.ttstrain.com/images/logo_wyomingbankers', N'Cheryl Johnston', N'307-638-5008', N'cheryl@wyomingbankers.com', N'307-638-5013', N'PO Box 2190', N'cheryl@wyomingbankers.com', N'307-638-5008', N'Cheryl Johnston', N'Weekly')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (11240, 1, N'http://www.ndba.com/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N'', N'', N'ndba', NULL, NULL, N'North Dakota Bankers Association', N'Aff       ', N'http://ttsmedia.ttstrain.com/images/logo_ndba', N'Dorothy Lick', N'701-223-5303', N'dorothy@ndba.com', NULL, N'PO Box 1438', N'dorothy@ndba.com', N'701-223-5303', N'Dorothy Lick', N'Weekly')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (11464, 1, N'http://www.cftnne.com/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N'', N'', N'cftea', NULL, NULL, N'Center for Financial Training & Education Alliance', N'billed', N'http://ttsmedia.ttstrain.com/images/logo_cftea', N'Tanya Kolonoski', N'888-366-3242', N'tanya@cftea.org', NULL, N'Auburn Hall Suite 303', N'tanya@cftea.org', N'888-366-3242', N'Tanya Kolonoski', N'Weekly')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (12014, 4, N'http://www.gregsouther.com/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N'', N'', N'gregsouther', NULL, NULL, N'Greg Souther Consulting', N'billed', N'http://ttsmedia.ttstrain.com/images/logo_gregsouther', N'Greg', N'770-851-8915', N'greg@gregsouther.com', N'707-267-3575', N'PO Box 1130', N'greg@gregsouther.com', N'770-851-8915', N'Greg', N'Daily')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (14577, 1, N'http://www.vabankers.org/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N' ', N' ', N'vabankers', NULL, NULL, N'Virginia  Bankers Association', N'Aff       ', N'http://ttsmedia.ttstrain.com/images/logo_vabankers', N'Courtney Fleming', N'804-819-4748', N'cfleming@vabankers.org', NULL, N'4490 Cox Road', N'cfleming@vabankers.org', N'804-819-4748', N'Courtney Fleming', N'None')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (16132, 1, N'http://www.rate-watch.com/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N' <div id="id16132">', N' <div id="id16132">', N'rate-watch', NULL, NULL, N'Rate-Watch', N'Aff       ', N'http://ttsmedia.ttstrain.com/images/logo_rate-watch', N'Brain', N'800-348-1831 x4294', N'Brian.Davis@rate-watch.com', NULL, N'1815 Janesville Avenue', N'Brian.Davis@rate-watch.com', N'800-348-1831 x4294', N'Brain', N'Daily')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (16392, 1, N'http://www.interaction-training.com/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N' ', N' ', N'interaction', NULL, NULL, N'Interaction Training', N'Aff       ', N'http://ttsmedia.ttstrain.com/images/logo_interaction', N'Honey', N'281-812-0211', N'honey@interaction-training.com', NULL, N'kk', N'honey@interaction-training.com', N'kk', N'Honey', N'None')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (17146, 1, N'http://www.ilbanker.com/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N' ', N' ', N'ilbanker', NULL, NULL, N'Illinois  Bankers Association', N'Aff       ', N'http://ttsmedia.ttstrain.com/images/logo_ilbanker', N'Brian Hoffman', N'217-789-9340', N'bhoffman@ilbanker.com', N'217-789-5410', N'524 South Second, Ste. 600', N'bhoffman@ilbanker.com', N'217-789-9340', N'Brian Hoffman', N'None')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (17147, 1, N'http://www.minnbankers.com/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N' ', N' ', N'minnbankers', NULL, NULL, N'Minnesota  Bankers Association', N'Aff       ', N'http://ttsmedia.ttstrain.com/images/logo_minnbankers', N'Kim Philipson', N'952-857-2632 ', N'kimp@minnbankers.com', N'952-896-1100', N'8050 Washington Ave. South', N'kimp@minnbankers.com', N'952-857-2632 ', N'Kim Philipson', N'None')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (17148, 1, N'http://www.ilfi.org/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N' ', N' ', N'ilfi', NULL, NULL, N'Illinois League of Financial Institutions', N'Aff       ', N'http://ttsmedia.ttstrain.com/images/logo_ilfi', N'Jane Stone', N'217-522-5575 x214', N'jstone@ilfi.org', NULL, N'133 S 4th St, Ste 206', N'jstone@ilfi.org', N'217-522-5575 x214', N'Jane Stone', N'None')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (17149, 1, N'http://www.nyba.com/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N' ', N' ', N'nyba', NULL, NULL, N'New York Bankers Association', N'Aff       ', N'http://ttsmedia.ttstrain.com/images/logo_nyba', N'Elisa Legg', N'212-297-1679', N'elegg@nyba.com', N'212-297-1683', N'99 Park Ave, 4th FL', N'elegg@nyba.com', N'212-297-1679', N'Elisa Legg', N'None')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (17150, 1, N'http://www.ctbank.com/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N' ', N' ', N'ctbank', NULL, NULL, N'Connecticut  Bankers Association', N'Aff       ', N'http://ttsmedia.ttstrain.com/images/logo_ctbank', N'Mary Beth Nelsen', N'860-677-5060', N'nelsenm@ctbank.com', N'860-677-5066', N'10 Waterside Dr # 300', N'nelsenm@ctbank.com', N'860-677-5060', N'Mary Beth Nelsen', N'None')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (17151, 1, N'http://www.massbankers.org/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N' ', N' ', N'massbankers', NULL, NULL, N'Massachusetts Bankers Association', N'Aff       ', N'http://ttsmedia.ttstrain.com/images/logo_massbankers', N'Tanya Duncan', N'617-523-7595', N'tduncan@massbankers.org', NULL, N'One Washington Mall, 8th Floor', N'tduncan@massbankers.org', N'617-523-7595', N'Tanya Duncan', N'None')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (17152, 1, N'http://www.nhbankers.com/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N' ', N' ', N'nhbankers', NULL, NULL, N'New Hampshire Bankers Association', N'Aff       ', N'http://ttsmedia.ttstrain.com/images/logo_nhbankers', N'Sandy Tracy', N'603-224-5373', N'stracy@nhbankers.com', N'603-224-3381', N'15 North Main St., Ste 204', N'stracy@nhbankers.com', N'603-224-5373', N'Sandy Tracy', N'None')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (17430, 1, N'http://www.wisbank.com', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N' ', N' ', N'wisbank', NULL, NULL, N'Wisconsin Bankers Association', N'Aff       ', N'http://ttsmedia.ttstrain.com/images/logo_wisbank', N'Patty Rogers', N'608.441.1200', N'progers@wisbank.com', NULL, N'4721 South Biltmore Lane', N'progers@wisbank.com', N'608.441.1200', N'Patty Rogers', N'None')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (17431, 1, N'http://www.njbankers.com/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N' ', N' ', N'njbankers', NULL, NULL, N'New Jersey Bankers Association', N'Aff       ', N'http://ttsmedia.ttstrain.com/images/logo_njbankers', N'Cris Goncalves', N'908-272-8500 x630', N'cgoncalves@njbankers.com', N'908-272-2720', N'411 North Avenue East', N'jzorn@njbankers.com', N'908-272-8500', N'Jenn Zorn', N'None')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (19741, 1, N'http://www.arkbankers.org/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N' ', N' ', N'arkbankers', NULL, NULL, N'Arkansas Bankers Association', N'Aff', N'http://ttsmedia.ttstrain.com/images/logo_arkbankers', N'Kami Taylor Coleman', N'501-376-3741', N'kami.taylor@arkbankers.org', N'501-376-9243', N'1220 West Third Street ', NULL, NULL, NULL, N'Daily')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (20385, 1, N'http://www.montanabankers.com', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N' ', N' ', N'montanabankers', NULL, NULL, N'Montana Bankers Association', N'Aff', N'http://ttsmedia.ttstrain.com/images/logo_montanabankers', N'Pam O''Reilly', N'406-441-4703', N'pam@montanabankers.com', N'', N'1 North Last Chance Gulch', NULL, NULL, NULL, N'Daily')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (21066, 4, N'http://www.wabankers.com', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N' ', N' ', N'wabankers', NULL, NULL, N'Washington Bankers Association', NULL, N'http://ttsmedia.ttstrain.com/images/logo_wabankers', N'Liz Wilson', N'206.344.3495', N'Liz@wabankers.com', N'206-223-6453', N'1601 Fifth Avenue', N'55', N'55', N'55', N'None')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (22805, 4, N' ', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N' ', N' ', N'newswatchmedia', N' ', N' ', N'NewsWatchMedia', N'Aff', N'http://ttsmedia.ttstrain.com/images/logo_newswatchmedia', N'Scott Spiewak', N'201-871-0427', N'scottspiewak@newswatchmedia.com', N' ', NULL, NULL, NULL, NULL, N'None')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (23801, 1, N'http://www.nmbankers.com', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N' ', N' ', N'nmbankers', NULL, NULL, N'New Mexico Bankers Association', N'Aff', N'http://ttsmedia.ttstrain.com/images/logo_nmbankers', N'Debbie Schaefer', N'505-822-7900', N'dschaefer@nmbankers.com', N' ', N' ', N'DSchaefer@nmbankers.com', N' ', N'DSchaefer@nmbankers.com', N'Daily')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (24033, 1, N'http://www.calbankers.com', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N' ', N' ', N'calbankers', NULL, NULL, N'California Bankers Association', N'Aff', N'http://ttsmedia.ttstrain.com/images/logo_calbankers', N'Laurie Eaton', N'916-438-4400', N'leaton@calbankers.com', N' ', N' ', N'leaton@calbankers.com', N'916-438-4400', N'  ', N'None')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (24870, 4, N'http://auroratrainingadvantage.com/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N' ', N' ', N'auroratraining', NULL, NULL, N'Aurora Training Advantage', N'Aff', N'http://ttsmedia.ttstrain.com/images/logo_auroratraining', N'Isaac Freeman', N'555', N'auroratrainingadvantage@gmail.com', N'55', N'55', N'auroratrainingadvantage@gmail.com', N'55', NULL, N'None')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (25993, 4, N'http://trainingpitstop', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N' ', N' ', N'trainingpitstop', NULL, NULL, N'Training Pitstop', N'Aff', N'http://ttsmedia.ttstrain.com/images/logo_trainingpitstop', N'Sanal Panikkal', N'+91 8884000156', N'sanal@trainingpitstop.com', NULL, N'Panikkal House, No.7 (Old # 422)', NULL, NULL, NULL, N'None')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (26276, 1, N'http://wwwiowabankers.com/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N' ', N' ', N'iowabankers', NULL, NULL, N'Iowa Bankers Association', N'Aff', N'http://ttsmedia.ttstrain.com/images/logo_iowabankers', N'Darcy Burnett', N'515-286-4352', N'dburnett@iowabankers.com', NULL, N'add', N'dburnett@iowabankers.com', N'dd', NULL, N'Daily')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (26966, 1, N' http://www.sdspec.com/', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N'', N'', N'spspec', NULL, NULL, N'Safe Deposit Specialists', N'Aff', N'http://ttsmedia.ttstrain.com/images/logo_spspec', N'David McGuinn', N'608-849-5563', N'affiliate@ttstrain.com', N'', N'PO Box 310', N'affiliate@ttstrain.com', N'608-849-5563', N'Mark', N'None')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (27391, 4, N'http://www.kybanks.org/Homepage/Contact.aspx', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N' ', N' ', N'kybanks', NULL, NULL, N'Kentucky Bankers Association', N'Aff', N'http://ttsmedia.ttstrain.com/images/logo_kybanks', N'Paula J. Cross', N'502-736-1276', N'pcross@kybanks.com', N'502-584-6390 ', N'600 W. Main Street, Suite 400 ', N'pcross@kybanks.com', N'502-736-1276 (Direct)', N'Paula Cross', N'Daily')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (27842, 4, N'www.ksbankers.com', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N' ', N' ', N'ksbankers', NULL, NULL, N'Kansas Bankers Association', NULL, N'http://ttsmedia.ttstrain.com/images/logo_ksbankers', N'Becky S. Tongish', N'(785)232-3444', N'btongish@ksbankers.com', NULL, N'610 Corporate View, P.O. Box 4407NULL', NULL, NULL, NULL, N'None')
GO
INSERT [dbo].[Affiliate] ([idUserAff], [CommissionModel], [URL], [WebBanner], [WebFooter], [EmailBanner], [EmailFooter], [ttsDomain], [GAPass], [supportEmail], [DisplayTitle], [BillingModel], [Logo], [ContactPerson], [ContactPhone], [ContactEmail], [ContactFax], [ContactAddress], [TechEmail], [TechPhone], [TechName], [EmailPromo]) VALUES (31267, 1, N'www.cunews.com', N'', N'<p>PO Box 310 . Waunakee, Wisconsin . 53597<br><strong>phone:</strong> <a href="tel:8008310678" class="tele">800.831.0678</a><br><strong>fax:</strong> 800.831.3776<br><strong>email:</strong> <a href="mailto:support@bankwebinars.com">support@bankwebinars.com</a></p>~<ul class="social"><li><a class="socicon small facebook" href="http://www.facebook.com/home.php#!/pages/Total-Training-Solutions/300546163412" target="_blank" data-placement="bottom" title="Follow us on Facebook"></a></li><li><a class="socicon small twitterbird" href="http://twitter.com/#!/ttstrain" target="_blank" data-placement="bottom" title="Follow us on Twitter"></a></li><li><a class="socicon small linkedin" href="https://www.linkedin.com/company/bankwebinars.com" target="_blank" data-placement="bottom" title="Follow us on LinkedIn"></a></li></ul>', N' ', N' ', N'cunews', NULL, NULL, N'Credit Union tech-talk', N'billed', N'http://ttsmedia.ttstrain.com/images/logo_cunews', N'Thomas Wright', N'55', N'twright@cunews.com', N'  ', N'  ', N'  ', N'  ', N'  ', N'None')
GO

select * FROM dbo.[Order]
