namespace CUWebinars.Business.Models
{
    //Instances will serve both 'AdditionalLocations' (billable)
    // and legacy's idea of 'AlternateEmails'. - the non-billable
    // method of sharing any notifications generated by the Order
    // for purely Admin (non-billable) purposes.

    public partial class AdditionalEmails
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string FullName { get; set; }
        public bool Billable { get; set; }
        public int idAdditionalLocation { get; set; }
        public virtual AdditionalLocations AdditionalLocations { get; set; }
    }
}
