//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTSWorker
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdGroupCriterion
    {
        public string Id { get; set; }
        public string adGroupId { get; set; }
        public string criterionUse { get; set; }
        public string criterion_id { get; set; }
        public string criterion_type { get; set; }
        public string criterion_ageRangeType { get; set; }
        public string criterion_genderType { get; set; }
        public string criterion_text { get; set; }
        public string criterion_matchType { get; set; }
        public string criterion_mobileAppCategoryId { get; set; }
        public string criterion_displayName { get; set; }
        public string criterion_appid { get; set; }
        public string criterion_URL { get; set; }
        public string criterion_conditions_argument { get; set; }
        public string criterion_conditions_operand { get; set; }
        public string criterion_userInterestId { get; set; }
        public string criterion_userInterestName { get; set; }
        public string criterion_userListId { get; set; }
        public string criterion_userListName { get; set; }
        public string criterion_userListMembershipStatus { get; set; }
        public string criterion_verticalid { get; set; }
        public string criterion_verticalparentid { get; set; }
        public string criterion_path { get; set; }
        public Nullable<decimal> criterion_criteriaCoverage { get; set; }
        public string criterion_criteriaSamples { get; set; }
    }
}
