//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTSWorker
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdGroupAd
    {
        public string Id { get; set; }
        public string ad_id { get; set; }
        public string ad_url { get; set; }
        public string ad_displayUrl { get; set; }
        public string ad_disapprovalReasons { get; set; }
        public string ad_name { get; set; }
        public string ad_type { get; set; }
        public string ad_description1 { get; set; }
        public string ad_description2 { get; set; }
        public string ad_image_mediaId { get; set; }
        public string ad_image_type { get; set; }
        public string ad_image_data { get; set; }
        public string ad_adToCopyImageFrom { get; set; }
        public string ad_headline { get; set; }
        public string ad_description { get; set; }
        public string ad_markupLanguages { get; set; }
        public string ad_mobileCarriers { get; set; }
        public string ad_businessName { get; set; }
        public string ad_countryCode { get; set; }
        public string ad_phoneNumber { get; set; }
        public string ad_promotionLine { get; set; }
        public string ad_snippet { get; set; }
        public string ad_impressionBeaconUrl { get; set; }
        public Nullable<int> ad_adDuration { get; set; }
        public string ad_certifiedVendorFormatId { get; set; }
        public string ad_sourceUrl { get; set; }
        public string ad_richMediaAdType { get; set; }
        public string ad_templateid { get; set; }
        public string ad_templateelements { get; set; }
        public Nullable<int> ad_duration { get; set; }
        public string experimentdata_experimentId { get; set; }
        public string experimentdata_experimentDeltaStatus { get; set; }
        public string experimentdata_experimentDataStatus { get; set; }
        public string experimentdata_experimentBidMultipliers_AdGroupExperimentBidMultipliersType { get; set; }
        public string experimentdata_experimentBidMultipliers_maxCpcMultiplier { get; set; }
        public string experimentdata_experimentBidMultipliers_maxContentCpcMultiplier { get; set; }
        public string experimentdata_experimentBidMultipliers_maxContentCpmMultiplier { get; set; }
        public string status { get; set; }
        public string approvalStatus { get; set; }
        public Nullable<bool> trademarkDisapproved { get; set; }
        public string stats_startDate { get; set; }
        public string stats_endDate { get; set; }
        public string stats_network { get; set; }
        public Nullable<int> stats_clicks { get; set; }
        public Nullable<int> stats_impressions { get; set; }
        public string stats_cost_comparablevaluetype { get; set; }
        public Nullable<int> stats_cost_microamount { get; set; }
        public Nullable<decimal> stats_averageposition { get; set; }
        public string stats_averagecpc_comparablevaluetype { get; set; }
        public Nullable<int> stats_averagecpc_microamount { get; set; }
        public string stats_averagecpm_comparablevaluetype { get; set; }
        public Nullable<int> stats_averagecpm_microamount { get; set; }
        public Nullable<decimal> stats_ctr { get; set; }
        public Nullable<int> stats_conversions { get; set; }
        public Nullable<int> stats_viewthroughconversions { get; set; }
        public string stats_statstype { get; set; }
        public Nullable<decimal> stats_percentServed { get; set; }
    }
}
