//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTSWorker
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdGroup
    {
        public string Id { get; set; }
        public string name { get; set; }
        public string campaignid { get; set; }
        public string campaignname { get; set; }
        public string status { get; set; }
        public string setting_settingtype { get; set; }
        public string setting_details_criterionTypeGroup { get; set; }
        public Nullable<bool> setting_details_targetAll { get; set; }
        public string bids_AdGroupBidsType { get; set; }
        public string bids_proxyKeywordMaxCpc_amount_comparablevaluetype { get; set; }
        public Nullable<int> bids_proxyKeywordMaxCpc_amount_microamount { get; set; }
        public Nullable<bool> bids_enhancedCpcEnabled { get; set; }
        public string bids_targetCpa_amount_comparablevaluetype { get; set; }
        public Nullable<int> bids_targetCpa_amount_microamount { get; set; }
        public string bids_conversionOptimizerBidType { get; set; }
        public string bids_keywordMaxCpc_amount_comparablevaluetype { get; set; }
        public Nullable<int> bids_keywordMaxCpc_amount_microamount { get; set; }
        public string bids_keywordContentMaxCpc_amount_comparablevaluetype { get; set; }
        public Nullable<int> bids_keywordContentMaxCpc_amount_microamount { get; set; }
        public string bids_maxCpm_amount_comparablevaluetype { get; set; }
        public Nullable<int> bids_maxCpm_amount_microamount { get; set; }
        public string bids_percentCpa_amount_comparablevaluetype { get; set; }
        public Nullable<int> bids_percentCpa_amount_microamount { get; set; }
        public string experimentdata_experimentId { get; set; }
        public string experimentdata_experimentDeltaStatus { get; set; }
        public string experimentdata_experimentDataStatus { get; set; }
        public string experimentdata_experimentBidMultipliers_AdGroupExperimentBidMultipliersType { get; set; }
        public string experimentdata_experimentBidMultipliers_maxCpcMultiplier { get; set; }
        public string experimentdata_experimentBidMultipliers_maxContentCpcMultiplier { get; set; }
        public string experimentdata_experimentBidMultipliers_maxContentCpmMultiplier { get; set; }
        public string stats_startDate { get; set; }
        public string stats_endDate { get; set; }
        public string stats_network { get; set; }
        public Nullable<int> stats_clicks { get; set; }
        public Nullable<int> stats_impressions { get; set; }
        public string stats_cost_comparablevaluetype { get; set; }
        public Nullable<int> stats_cost_microamount { get; set; }
        public Nullable<decimal> stats_averageposition { get; set; }
        public string stats_averagecpc_comparablevaluetype { get; set; }
        public Nullable<int> stats_averagecpc_microamount { get; set; }
        public string stats_averagecpm_comparablevaluetype { get; set; }
        public Nullable<int> stats_averagecpm_microamount { get; set; }
        public Nullable<decimal> stats_ctr { get; set; }
        public Nullable<int> stats_conversions { get; set; }
        public Nullable<int> stats_viewthroughconversions { get; set; }
        public string stats_statstype { get; set; }
    }
}
