//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTSWorker
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarEvent
    {
        public string Id { get; set; }
        public string CalendarId { get; set; }
        public string Summary { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public Nullable<bool> AllDayEvent { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<System.DateTime> OriginalStartTimeDateTime { get; set; }
        public Nullable<bool> SendNotification { get; set; }
        public string Kind { get; set; }
        public string ETag { get; set; }
        public string Status { get; set; }
        public string HTMLLink { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<int> ColorId { get; set; }
        public string CreatorEmail { get; set; }
        public string CreatorDisplayName { get; set; }
        public string OrganizerEmail { get; set; }
        public string OrganizerDisplayName { get; set; }
        public string Recurrences { get; set; }
        public string RecurringEventId { get; set; }
        public string Transparency { get; set; }
        public string Visibility { get; set; }
        public string iCalUid { get; set; }
        public string Sequence { get; set; }
        public string AttendeesAggregate { get; set; }
        public string AttendeesEmails { get; set; }
        public string AttendeesDisplayNames { get; set; }
        public Nullable<bool> AttendeesOmitted { get; set; }
        public string ExtendedPropPrivateKey { get; set; }
        public string ExtendedPropPrivateVal { get; set; }
        public string ExtendedPropSharedKey { get; set; }
        public string ExtendedPropSharedVal { get; set; }
        public string GadgetAggregate { get; set; }
        public Nullable<bool> AnyoneCanAddSelf { get; set; }
        public Nullable<bool> GuestsCanInviteOthers { get; set; }
        public Nullable<bool> GuestsCanSeeOtherGuests { get; set; }
        public Nullable<bool> PrivateCopy { get; set; }
        public Nullable<bool> RemindersUseDefault { get; set; }
        public string ReminderOverrideMethods { get; set; }
        public string ReminderOverrideMinutes { get; set; }
    }
}
