//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTSWorker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendar
    {
        public string Id { get; set; }
        public string Summary { get; set; }
        public string Description { get; set; }
        public string Kind { get; set; }
        public string ETag { get; set; }
        public string Location { get; set; }
        public string Timezone { get; set; }
        public string SummaryOverride { get; set; }
        public Nullable<int> ColorId { get; set; }
        public Nullable<bool> Hidden { get; set; }
        public Nullable<bool> Selected { get; set; }
        public string AccessRole { get; set; }
        public string ReminderMethods { get; set; }
        public string ReminderMinutes { get; set; }
    }
}
