//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTSWorker
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignCriterion
    {
        public string Id { get; set; }
        public string adGroupId { get; set; }
        public string criterionUse { get; set; }
        public string criterion_id { get; set; }
        public string criterion_type { get; set; }
        public string criterion_dayofweek { get; set; }
        public Nullable<int> criterion_starthour { get; set; }
        public string criterion_startminute { get; set; }
        public Nullable<int> criterion_endhour { get; set; }
        public string criterion_endminute { get; set; }
        public string criterion_ageRangeType { get; set; }
        public string criterion_name { get; set; }
        public string criterion_countrycode { get; set; }
        public string criterion_contentLabelType { get; set; }
        public string criterion_genderType { get; set; }
        public string criterion_text { get; set; }
        public string criterion_matchType { get; set; }
        public string criterion_code { get; set; }
        public string criterion_locationname { get; set; }
        public string criterion_displayname { get; set; }
        public string criterion_targetingstatus { get; set; }
        public string criterion_mobileAppCategoryId { get; set; }
        public string criterion_appid { get; set; }
        public string criterion_deviceName { get; set; }
        public string criterion_manufacturerName { get; set; }
        public string criterion_deviceType { get; set; }
        public string criterion_operatingSystemName { get; set; }
        public Nullable<int> criterion_osMajorVersion { get; set; }
        public Nullable<int> criterion_osMinorVersion { get; set; }
        public string criterion_operatorType { get; set; }
        public string criterion_URL { get; set; }
        public string criterion_platformName { get; set; }
        public string criterion_conditions_argument { get; set; }
        public string criterion_conditions_operand { get; set; }
        public Nullable<int> criterion_radiusDistanceUnits { get; set; }
        public Nullable<decimal> criterion_radiusInUnits { get; set; }
        public string criterion_userInterestId { get; set; }
        public string criterion_userInterestName { get; set; }
        public string criterion_userListId { get; set; }
        public string criterion_userListName { get; set; }
        public string criterion_userListMembershipStatus { get; set; }
        public string criterion_verticalid { get; set; }
        public string criterion_verticalparentid { get; set; }
        public string criterion_path { get; set; }
        public Nullable<decimal> criterion_criteriaCoverage { get; set; }
        public string criterion_criteriaSamples { get; set; }
        public string criterion_address_streetaddress { get; set; }
        public string criterion_address_streetaddress2 { get; set; }
        public string criterion_address_cityname { get; set; }
        public string criterion_address_provincecode { get; set; }
        public string criterion_address_provincename { get; set; }
        public string criterion_address_postalcode { get; set; }
        public string criterion_address_countrycode { get; set; }
        public Nullable<int> criterion_geopoint_latitudeinmicrodegrees { get; set; }
        public Nullable<int> criterion_geopoint_longitudeinmicrodegrees { get; set; }
        public Nullable<int> criterion_verticies_latitudeinmicrodegrees { get; set; }
        public Nullable<int> criterion_verticies_longitudeinmicrodegrees { get; set; }
        public string totalNumEntries { get; set; }
    }
}
