//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTSWorker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign
    {
        public string Id { get; set; }
        public string name { get; set; }
        public string status { get; set; }
        public string servingstatus { get; set; }
        public string startdate { get; set; }
        public string enddate { get; set; }
        public Nullable<int> totalnumentries { get; set; }
        public string adservingoptimizationstatus { get; set; }
        public string biddingstrategy_biddingstrategytype { get; set; }
        public string biddingstrategy_pricingModel { get; set; }
        public string biddingstrategy_conversionOptimizerBidType { get; set; }
        public string biddingstrategy_enhancedcpcenabled { get; set; }
        public string biddingstrategy_bidCeiling_comparablevaluetype { get; set; }
        public string biddingstrategy_bidCeiling_microamount { get; set; }
        public string budget_budgetid { get; set; }
        public string budget_name { get; set; }
        public string budget_period { get; set; }
        public string budget_amount_comparablevaluetype { get; set; }
        public Nullable<int> budget_amount_microamount { get; set; }
        public string budget_deliverymethod { get; set; }
        public Nullable<int> budget_referencecount { get; set; }
        public string budget_status { get; set; }
        public string campaignstats_startDate { get; set; }
        public string campaignstats_endDate { get; set; }
        public string campaignstats_network { get; set; }
        public Nullable<int> campaignstats_clicks { get; set; }
        public Nullable<int> campaignstats_impressions { get; set; }
        public string campaignstats_cost_comparablevaluetype { get; set; }
        public Nullable<int> campaignstats_cost_microamount { get; set; }
        public Nullable<decimal> campaignstats_averageposition { get; set; }
        public string campaignstats_averagecpc_comparablevaluetype { get; set; }
        public Nullable<int> campaignstats_averagecpc_microamount { get; set; }
        public string campaignstats_averagecpm_comparablevaluetype { get; set; }
        public Nullable<int> campaignstats_averagecpm_microamount { get; set; }
        public Nullable<decimal> campaignstats_ctr { get; set; }
        public Nullable<int> campaignstats_conversions { get; set; }
        public Nullable<int> campaignstats_viewthroughconversions { get; set; }
        public string campaignstats_statstype { get; set; }
        public Nullable<bool> conversionoptimizereligibility_eligible { get; set; }
        public string conversionoptimizereligibility_rejectionreasons { get; set; }
        public Nullable<int> frequencycap_impressions { get; set; }
        public string frequencycap_level { get; set; }
        public string frequencycap_timeunit { get; set; }
        public string settings_settingtype { get; set; }
        public Nullable<bool> settings_optin { get; set; }
        public Nullable<bool> settings_useAdGroup { get; set; }
        public string settings_trackingUrl { get; set; }
        public string settings_positivegeotargettype { get; set; }
        public string settings_negativegeotargettype { get; set; }
        public Nullable<bool> networksetting_targetgooglesearch { get; set; }
        public Nullable<bool> networksetting_targetsearchnetwork { get; set; }
        public Nullable<bool> networksetting_targetcontentnetwork { get; set; }
        public Nullable<bool> networksetting_targetpartnersearchnetwork { get; set; }
        public string totalbudget_budgetid { get; set; }
        public string totalbudget_name { get; set; }
        public string totalbudget_period { get; set; }
        public string totalbudget_amount_comparablevaluetype { get; set; }
        public Nullable<int> totalbudget_amount_microamount { get; set; }
        public string totalbudget_deliverymethod { get; set; }
        public Nullable<int> totalbudget_referencecount { get; set; }
        public string totalbudget_status { get; set; }
    }
}
