//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTSWorker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public string Id { get; set; }
        public string Fullname { get; set; }
        public string NamePrefix { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string NameSuffix { get; set; }
        public string Nickname { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Anniversaries { get; set; }
        public string CustomEventTypes { get; set; }
        public string CustomEvents { get; set; }
        public string Gender { get; set; }
        public string Groups { get; set; }
        public string OrganizationName { get; set; }
        public string OrganizationTitle { get; set; }
        public string Photo { get; set; }
        public string Notes { get; set; }
        public string HomeEmailAddresses { get; set; }
        public string WorkEmailAddresses { get; set; }
        public string CustomEmailAddressTypes { get; set; }
        public string CustomEmailAddresses { get; set; }
        public string HomePhoneNumbers { get; set; }
        public string WorkPhoneNumbers { get; set; }
        public string MobilePhoneNumbers { get; set; }
        public string GoogleVoicePhoneNumbers { get; set; }
        public string HomeFaxes { get; set; }
        public string WorkFaxes { get; set; }
        public string Pagers { get; set; }
        public string CustomPhoneNumberTypes { get; set; }
        public string CustomPhoneNumbers { get; set; }
        public string HomeAddresses { get; set; }
        public string WorkAddresses { get; set; }
        public string CustomAddressTypes { get; set; }
        public string CustomAddresses { get; set; }
        public string BillingInfo { get; set; }
        public string RelationTypes { get; set; }
        public string RelationValues { get; set; }
        public string IMTypes { get; set; }
        public string IMValues { get; set; }
        public string WebsiteTypes { get; set; }
        public string WebsiteValues { get; set; }
        public string ETag { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string SelfLink { get; set; }
        public string EditLink { get; set; }
    }
}
