//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTSWorker
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactGroup
    {
        public string Id { get; set; }
        public string Group { get; set; }
        public string SystemGroup { get; set; }
        public string ETag { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string SelfLink { get; set; }
    }
}
