//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTSWorker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direction
    {
        public string Id { get; set; }
        public string StartAddress { get; set; }
        public string EndAddress { get; set; }
        public string Duration { get; set; }
        public string Distance { get; set; }
        public string StartLocation { get; set; }
        public string EndLocation { get; set; }
        public string TravelMode { get; set; }
        public string StepHTMLInstructions { get; set; }
        public string StepDistance { get; set; }
        public string StepDuration { get; set; }
        public string StepStartLocation { get; set; }
        public string StepEndLocation { get; set; }
    }
}
