//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTSWorker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public string Id { get; set; }
        public string ETag { get; set; }
        public string Title { get; set; }
        public string AuthorName { get; set; }
        public string AuthorEmail { get; set; }
        public string DocumentType { get; set; }
        public string Labels { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string LastModifiedByEmail { get; set; }
        public string LastModifiedByName { get; set; }
        public Nullable<System.DateTime> LastViewed { get; set; }
        public Nullable<System.DateTime> Published { get; set; }
        public string PDFLink { get; set; }
        public string WebLink { get; set; }
        public string ACLLink { get; set; }
        public string FolderId { get; set; }
        public string FolderName { get; set; }
    }
}
