//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTSWorker
{
    using System;
    using System.Collections.Generic;
    
    public partial class GDriveACL
    {
        public string PermissionId { get; set; }
        public string ResourceId { get; set; }
        public string Role { get; set; }
        public string Type { get; set; }
        public string Value { get; set; }
        public string AdditionalRoles { get; set; }
        public string ETag { get; set; }
    }
}
