//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTSWorker
{
    using System;
    using System.Collections.Generic;
    
    public partial class GDrive
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Formats { get; set; }
        public string Extension { get; set; }
        public string MIMEType { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> Size { get; set; }
        public string Owners { get; set; }
        public Nullable<bool> Folder { get; set; }
        public Nullable<bool> Starred { get; set; }
        public Nullable<bool> Restricted { get; set; }
        public Nullable<bool> Hidden { get; set; }
        public Nullable<bool> Trashed { get; set; }
        public Nullable<bool> Viewed { get; set; }
        public string ETag { get; set; }
        public string ParentIds { get; set; }
        public string ParentIsRoot { get; set; }
        public string ChildIds { get; set; }
        public string ChildLinks { get; set; }
    }
}
