//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTSWorker
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CalendarEvent> CalendarEvents { get; set; }
        public DbSet<Calendar> Calendars { get; set; }
        public DbSet<ContactGroup> ContactGroups { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<Document> Documents { get; set; }
        public DbSet<DocumentsACL> DocumentsACLs { get; set; }
        public DbSet<GDrive> GDrives { get; set; }
        public DbSet<GDriveACL> GDriveACLs { get; set; }
        public DbSet<Mailbox> Mailboxes { get; set; }
        public DbSet<MailMessage> MailMessages { get; set; }
        public DbSet<AdGroupAd> AdGroupAds { get; set; }
        public DbSet<AdGroupCriterion> AdGroupCriterions { get; set; }
        public DbSet<AdGroup> AdGroups { get; set; }
        public DbSet<CampaignCriterion> CampaignCriterions { get; set; }
        public DbSet<Campaign> Campaigns { get; set; }
        public DbSet<Direction> Directions { get; set; }
    }
}
