//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTSWorker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mailbox
    {
        public string Id { get; set; }
        public string Mailbox1 { get; set; }
        public string MessagesCount { get; set; }
        public string RecentMessagesCount { get; set; }
        public string Flags { get; set; }
    }
}
