//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTSWorker
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailMessage
    {
        public string Id { get; set; }
        public string Mailbox { get; set; }
        public string Subject { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string CC { get; set; }
        public string BCC { get; set; }
        public string Date { get; set; }
        public string MessageBody { get; set; }
        public string Attachments { get; set; }
        public string AttachmentData { get; set; }
        public string Size { get; set; }
        public string Flags { get; set; }
        public string Labels { get; set; }
        public string ThreadId { get; set; }
        public string MsgId { get; set; }
        public string PartIds { get; set; }
        public string PartFilenames { get; set; }
        public string PartContentTypes { get; set; }
        public string PartSizes { get; set; }
        public string Headers { get; set; }
    }
}
