//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUWebinars.Business.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CUWebinars.Business.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [master]
        ///GO
        ///IF EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE name = N&apos;CUWebinars&apos;)
        ///DROP DATABASE [CUWebinars];
        ///
        ///CREATE DATABASE [CUWebinars]
        ///ON (name=&apos;CUWebinars&apos;, filename=&apos;E:\CUWebinars.mdf&apos;)
        ///GO
        ///USE [CUWebinars]
        ///GO
        ///ALTER DATABASE [CUWebinars] SET COMPATIBILITY_LEVEL = 110
        ///GO
        ///IF (1 = FULLTEXTSERVICEPROPERTY(&apos;IsFullTextInstalled&apos;))
        ///begin
        ///EXEC [CUWebinars].[dbo].[sp_fulltext_database] @action = &apos;enable&apos;
        ///end
        ///GO
        ///ALTER DATABASE [CUWebinars] SET ANSI_NULL_DEFAULT OFF 
        ///GO
        ///ALTER DAT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateDb {
            get {
                return ResourceManager.GetString("CreateDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [master]
        ///GO
        ///IF EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE name = N&apos;MembershipReboot&apos;)
        ///DROP DATABASE [MembershipReboot];
        ///
        ///CREATE DATABASE [MembershipReboot] 
        ///ON (name=&apos;MembershipReboot&apos;, filename=&apos;E:\MembershipReboot.mdf&apos;)
        ///GO
        ///USE [MembershipReboot]
        ///GO
        ///ALTER DATABASE [MembershipReboot] SET COMPATIBILITY_LEVEL = 110
        ///GO
        ///IF (1 = FULLTEXTSERVICEPROPERTY(&apos;IsFullTextInstalled&apos;))
        ///begin
        ///EXEC [MembershipReboot].[dbo].[sp_fulltext_database] @action = &apos;enable&apos;
        ///end
        ///GO
        ///ALTER DATABASE [Memb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MemReboot {
            get {
                return ResourceManager.GetString("MemReboot", resourceCulture);
            }
        }
    }
}
