INSERT  BWClean.dbo.Affiliate
        ( idUserAff ,
          CommissionModel ,
          URL ,
          WebBanner ,
          WebFooter ,
          EmailBanner ,
          EmailFooter ,
          ttsDomain ,
          GAPass ,
          supportEmail ,
          DisplayTitle ,
          BillingModel ,
          Logo ,
          ContactPerson ,
          ContactPhone ,
          ContactEmail ,
          ContactFax ,
          ContactAddress ,
          TechEmail ,
          TechPhone ,
          TechName ,
          EmailPromo
        )
        SELECT  idUser ,
                CommissionModel ,
                URL ,
                WebBanner ,
                WebFooter ,
                EmailBanner ,
                EmailFooter ,
                ttsDomain ,
                GAPass ,
                supportEmail ,
                DisplayTitle ,
                BillingModel ,
                Logo ,
                ContactPerson ,
                ContactPhone ,
                ContactEmail ,
                ContactFax ,
                ContactAddress ,
                TechEmail ,
                TechPhone ,
                TechName ,
                EmailPromo
        FROM    TTSWebinars2.dbo.Affiliate